apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      compiler: c
  template:
    metadata:
      labels:
        compiler: c
spec:
  containers:
  - image: juananmora/gcc:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: Always
    restartPolicy: Never
    name: gcc





      
