apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      compiler: c
  template:
    metadata:
      labels:
        compiler: c
    spec:
      containers:
      - name: gcc
        image: juananmora/gcc:latest
        command:
         - /bin/sh
         - "-c"
         - "sleep 60m"
       restartPolicy: Never
       resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"





      
