apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: gcc
          image: 'juananmora/gcc:latest'
      
