apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcc
  labels:
    app: gcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcc
  template:
    metadata:
      labels:
        app: gcc
    spec:
      containers:
      - name: gcc
        image: juananmora/gcc:59







      
